### ISSUE TITLE
Need discussions feature enabled in the server and desktop repos

### ISSUE THREAD

**Issue by maxfield-allison** [persys-ai/persys#2]
Or maybe just on this one to keep all of that forum style info consolidated. 

Cleaner troubleshooting and easier to keep issues organized. Better place for helpful information from the community and filling in knowledge gaps from minimal documentation.

Was able to get the desktop app and server all running and connected btw. need to iron out chroma and ollama then I may create build instructions and a PR; assist with some documentation etc.

Hope you're doing well, dont forget to sleep!

**Comment by space0blaster** [comment]
Just opened up discussions on the org level, good thought. Let me know if there's any issues accessing it. Looking forward to the pull requests!

Sleeping now per doctor's orders!
